### ISSUE TITLE
remove the `start` script from Calendar-Widgets package

### ISSUE THREAD

**Issue by matthewbub** [matthewbub/calendar-widgets#88] opened 2023-04-11 19:15 UTC
This is confusing and causing unnecessary difficulties for folks getting started locally. The `start` script within the `/workspaces/calendar-widgets/package.json` file does nothing at all and should be removed from the project. We only need the build and lint commands.

**Comment by Ankan-cyber** [comment] 2023-04-12 05:57
@9mbs added pr for issue#88

**Comment by 9mbs** [comment] 2023-04-12 12:46
Thank you @Ankan-cyber !! This should fix potential confusions when folks are pulling up the project locally. Closing this issue as the problem is resolved 🙂

**Closed as completed by 9mbs** 2023-04-12 12:46 UTC
Labels: enhancement, help wanted, good first issue
